[package]
name = "sol"
version = "0.1.0"
authors = ["Miguel Taciano <contact@mtaciano.com>"]
edition = "2021"

[[bin]]
name = "ssc" # The Standard Sol Compiler
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
